apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  provider: kubernetes-monitoring

namespace: flux

resources:
  - resources/helm-repository.yaml
  # - resources/prometheus-helmrelease.yaml
  - resources/grafana-helmrelease.yaml
  # - resources/loki-helmrelease.yaml
  - resources/namespace.yaml
  